# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
  pull_request:
    branches: [ "main" ]
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Get version
      id: version
      uses: battila7/get-version-action@v2

    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build RabbitMQ.Server.MapedService/EBCEYS.RabbitMQ.Server.MappedService.csproj -c Release --no-restore -p:PackageVersion=${{ steps.version.outputs.version-without-v }}
    - name: Test
      run: dotnet test -c Release
      
    - name: Pack
      run: dotnet pack RabbitMQ.Server.MapedService/EBCEYS.RabbitMQ.Server.MappedService.csproj -c Release -p:PackageVersion=${{ steps.version.outputs.version-without-v }} --no-restore --no-build --include-symbols -p:SymbolPackageFormat=snupkg -o .

    - name: Push to NuGet
      run: dotnet nuget push *.nupkg --skip-duplicate -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_API_KEY}}

