# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET-tests

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore RabbitMQ.Server.MapedService/EBCEYS.RabbitMQ.Server.MappedService.csproj
    - name: Build
      run: dotnet build RabbitMQ.Server.MapedService/EBCEYS.RabbitMQ.Server.MappedService.csproj -c Release --no-restore
    - name: Test
      run: dotnet test EBCEYS.RabbitMQ.IntegrationTests/EBCEYS.RabbitMQ.IntegrationTests.csproj -c Release

